name: Sindre
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004a6f'
    - '#fefefe'
    - '#2b6e8b'
    - '#91a1a9'
    - '#c2c5b4'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
